FROM node:16.13.2-slim
#Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /usr/src/app/
RUN npm install
RUN npm audit fix
# If you are building your code for production
# RUN npm ci --only=production

ADD . /usr/src/app


EXPOSE 8080
CMD ["npm","start"]